name: connectivity_watcher
description: A Flutter package to check your internet connectivity with subsecond response times, even on mobile networks!.
version: 2.0.0
repository: "https://github.com/Oauth-Celestial/Connectivity_Watcher.git"

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
     
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
screenshots:
  - description: Connectivity Watcher
    path: assets/watcher.jpg
platforms:
  android:
  ios:



